enable-magisk-update = true
parallel-jobs = 1
build-mode = "apk"   
# FX
#[FX]
#apkmirror-dlurl="https://www.apkmirror.com/apk/nextapp-inc/fx-file-explorer/"
#uptodown-dlurl="https://fx-file-explorer.en.uptodown.com/android"
#patches-source="indrastorms/Dropped-Patches"
#cli-source="ReVanced/revanced-cli"
#build-mode="apk"
#version="latest"
# ReVanced"

# ReVanced Extended by anddea
[YouTube-anddea]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-version = "dev"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
version = "20.25.37"
patcher-args = "-e='Hide ads' -e='Alternative thumbnails' -e='Bypass image region restrictions' -e='Hide feed components' -e='Hide feed flyout menu' -e='Disable forced auto audio tracks' -e='Disable forced auto captions' -e='Hide layout components' -e='Remove viewer discretion dialog' -e='Hook download actions' -e='Change form factor' -e='Change live ring click action' -e='Enable gradient loading screen' -e='Hook YouTube Music actions' -e='Navigation bar components' -e='Disable sign in to TV popup' -OdarkThemeBackgroundColor='@android:color/black' -OlightThemeBackgroundColor='@android:color/white' -e='Snack bar components' -e='Disable splash animation' -e='Spoof app version' -e='Change start page' -e='Toolbar components' -e='Set Transcript Cookies' -e='Disable layout updates' -e='Hide Shorts dimming' -OdoubleTapLengthArrays='1,2,3,5,10,15,20,30,45,60,90,120,150,180' -e='Custom double tap length' -e='MaterialYou' -e='Theme' -e='Translations for YouTube' -e='Visual preferences icons for YouTube' -e='Hide accessibility controls dialog' -e='Remove background playback restrictions' -e='Enable debug logging' -e='Bypass URL redirects' -e='Open links externally' -e='Disable QUIC protocol' -e='Change share sheet' -e='Sanitize sharing links' -e='Spoof watch history' -e='Hide action buttons' -e='Ambient mode control' -e='Hide player buttons' -e='Hide comments components' -e='Player components' -e='Description components' -e='Hide player flyout menu' -e='Change player flyout menu toggles' -e='Fullscreen components' -e='Disable haptic feedback' -e='Miniplayer' -e='Disable resuming Miniplayer on startup' -e='Overlay buttons' -e='Seekbar components' -e='Shorts components' -e='Disable resuming Shorts on startup' -e='Swipe controls' -e='GmsCore support' -e='Return YouTube Dislike' -e='Return YouTube Username' -OrvxSettingsLabel='ReVanced Extended' -e='Settings for YouTube' -e='SponsorBlock' -e='Video playback' --continue-on-error "
# Morphe
##[YouTube-Morphe]
#app-name = "YouTube"
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#patches-source = "MorpheApp/morphe-patches"
#cli-source = "MorpheApp/morphe-cli"
#rv-brand = "Morphe"
#build-mode = "both"

